#!/bin/bash

step=12
file=/sys/class/leds/chromeos::kbd_backlight/brightness

case "$1" in
    -i|--increase) ((val = +step));;
    -d|--decrease) ((val = -step));;
esac

if !((val)); then
    echo "Increase or decrease screen brighness"
    echo "Usage: ${0##*/} --increase | --decrease"
    exit
fi

read -r cur < "$file"    
((val = cur + val))

if ((val <   0)); then ((val =   0)); fi
if ((val > 100)); then ((val = 100)); fi

printf '%d' "$val" > "$file"

printf 'Before: %3d\n' "$cur"
printf 'After : %3d\n' "$val"
